apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: /pos-order-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3004"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: pos-secrets
              key: mongo-order-uri
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: pos-secrets
              key: rabbitmq-url
        - name: RABBITMQ_EXCHANGE
          value: "pos_events"
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP
