apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-config
data:
  # Common settings
  NODE_ENV: "production"
  RABBITMQ_EXCHANGE: "pos_events"
  
  # Service URLs for API Gateway
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  INVENTORY_SERVICE_URL: "http://inventory-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  STORE_SERVICE_URL: "http://store-service:3006"
  SYNC_SERVICE_URL: "http://sync-service:3007"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3008"
  
  # Redis configuration
  REDIS_URL: "redis://redis:6379"
  
  # Email configuration
  MAIL_HOST: "smtp.example.com"
  MAIL_PORT: "587"
